version: "3"

services:
  ros-rplidar:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    privileged: true
    image: ros-rplidar
    container_name: ros-rplidar
    command:
      [
        "bash",
        "-c",
        "source /opt/ros/ros_ws/devel/setup.bash && roslaunch /opt/ros/ros_ws/src/rplidar_ros/launch/rplidar.launch",
      ]
    devices:
      - /dev/ttyUSB0
    network_mode: host
