version: "2.3"

services:
  ros-rplidar:
    build:
      context: ../../  
      dockerfile: ./Dockerfile
    tty: true
    privileged: true
    command:
      - bash
      - -c
      - |
        source /opt/ros/ros_ws/devel/setup.bash
        export ROS_MASTER_URI=http://127.0.0.1:11311
        roslaunch /opt/ros/ros_ws/src/rplidar_ros/launch/rplidar.launch
    devices:
      - /dev/ttyUSB0

  rviz-intel:
    image: rosbot_remote/rviz:latest    
    environment: 
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  rviz-nvidia:
    image: rosbot_remote/rviz:latest
    runtime: nvidia    
    environment: 
        - DISPLAY
        - NVIDIA_VISIBLE_DEVICES=all
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix:rw