x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file: .env

x-rplidar-image: &rplidar-image
  image: husarion/rplidar:jazzy
  # build:
  #   context: ..
  #   dockerfile: Dockerfile

services:
  rplidar-serial:
    profiles: [serial]
    <<: [*rplidar-image, *common-config]
    devices:
      - ${RPLIDAR_SERIAL_DEVICE:-/dev/ttyUSB0}
    command: >
      ros2 launch /husarion_utils/rplidar.launch.yaml
        channel_type:=serial
        serial_baudrate:=${RPLIDAR_BAUDRATE:?set RPLIDAR_BAUDRATE in demo/.env (see README for your model)}

  rplidar-tcp:
    profiles: [tcp]
    <<: [*rplidar-image, *common-config]
    command: >
      ros2 launch /husarion_utils/rplidar.launch.yaml
        channel_type:=tcp
        tcp_ip:=${RPLIDAR_TCP_IP:?set RPLIDAR_TCP_IP in demo/.env}
        tcp_port:=${RPLIDAR_TCP_PORT:?set RPLIDAR_TCP_PORT in demo/.env}

  rplidar-udp:
    profiles: [udp]
    <<: [*rplidar-image, *common-config]
    command: >
      ros2 launch /husarion_utils/rplidar.launch.yaml
        channel_type:=udp
        udp_ip:=${RPLIDAR_UDP_IP:?set RPLIDAR_UDP_IP in demo/.env}
        udp_port:=${RPLIDAR_UDP_PORT:?set RPLIDAR_UDP_PORT in demo/.env}

  rviz:
    image: husarion/rviz2:jazzy
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
      - ./rviz.launch.py:/ros2_ws/rviz.launch.py
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      ros2 launch rviz.launch.py
