x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file: .env

services:
  rplidar:
    # image: husarion/rplidar:humble
    build:
      context: ..
      dockerfile: Dockerfile
    <<: *common-config
    devices:
      - /dev/ttyUSB0
    command: >
      ros2 launch sllidar_ros2 sllidar_launch.py
        serial_baudrate:=${RPLIDAR_BAUDRATE:-115200}
        device_namespace:=lidar

  rviz:
    image: husarion/rviz2:humble
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
      - ./rviz.launch.py:/ros2_ws/rviz.launch.py
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      ros2 launch rviz.launch.py
        device_namespace:=lidar
