x-common-config:
  &common-config
  network_mode: host
  ipc: host
  env_file: .env

services:
  rplidar:
    image: husarion/rplidar:jazzy
    # build:
    #   context: ..
    #   dockerfile: Dockerfile
    <<: *common-config
    # Serial models only - drop this `devices:` block for IP-based models (T1/S2E/S1_TCP).
    devices:
      - /dev/ttyUSB0
    command: >
      ros2 launch /husarion_utils/rplidar.launch.yaml
        channel_type:=serial
        serial_baudrate:=${RPLIDAR_BAUDRATE:?Error: baudrate unset in .env}

  # rplidar-udp:
  #   image: husarion/rplidar:humble
  #   <<: *common-config
  #   command: >
  #     ros2 launch /husarion_utils/rplidar.launch.yaml
  #       channel_type:=udp
  #       udp_ip:=${RPLIDAR_UDP_IP:?Error: UDP IP unset in .env}
  #       udp_port:=${RPLIDAR_UDP_PORT:?Error: UDP port unset in .env}
  #       scan_mode:=Sensitivity
  #
  # rplidar-tcp:
  #   image: husarion/rplidar:humble
  #   <<: *common-config
  #   command: >
  #     ros2 launch /husarion_utils/rplidar.launch.yaml
  #       channel_type:=tcp
  #       tcp_ip:=${RPLIDAR_TCP_IP:?Error: TCP IP unset in .env}
  #       tcp_port:=${RPLIDAR_TCP_PORT:?Error: TCP port unset in .env}

  rviz:
    image: husarion/rviz2:jazzy
    <<: *common-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
      - ./rviz.launch.py:/ros2_ws/rviz.launch.py
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
    command: >
      ros2 launch rviz.launch.py
