name: Build/Publish Docker Image 

on: push
  # push:
  #   branches:
  #     - 'ros2'
  
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ros-distro: [foxy, galactic, humble]

    steps:
    - name: Display branch name
      run: echo ${GITHUB_REF##*/}

    - name: Display branch name 2
      run: echo ${{ github.ref }}


    - name: Display branch name 3
      run: echo ${{ github.base_ref }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    
    - name: Login to Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build and push
      if: github.ref.name == 'main'
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64, linux/amd64
        build-args: ROS_DISTRO=${{ matrix.ros-distro }}
        push: true
        tags: husarion/rplidar:${{ matrix.ros-distro }}
        cache-from: type=registry,ref=husarion/rplidar:${{ matrix.ros-distro }}
        cache-to: type=inline

    - name: Build and push
      if: github.ref.name != 'main'
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm64, linux/amd64
        build-args: ROS_DISTRO=${{ matrix.ros-distro }}
        push: true
        tags: husarion/rplidar:${{ matrix.ros-distro }}-${{ github.ref.name }}
        cache-from: type=registry,ref=husarion/rplidar:${{ matrix.ros-distro }}-${{ github.ref.name }}
        cache-to: type=inline